# Cloud Build configuration for Google Cloud Run
# This file allows building directly in the cloud without local Docker

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bureaucracy-breaker:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bureaucracy-breaker:latest'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bureaucracy-breaker:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bureaucracy-breaker:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bureaucracy-breaker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bureaucracy-breaker:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'GOOGLE_GENAI_API_KEY=GOOGLE_GENAI_API_KEY:latest'

images:
  - 'gcr.io/$PROJECT_ID/bureaucracy-breaker:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/bureaucracy-breaker:latest'

# Build timeout - 20 minutes should be enough
timeout: '1200s'
